### ISSUE TITLE
Should refer to this repository instead Zed's main repository? (in `extension.toml`)

### ISSUE THREAD

**Issue by l2D** [wingyplus/zed-powershell#4]
Hi Wingyplus,

From the issue's title, what do you think?

![20240908_1210PM_mGGkjJMF@2x](https://github.com/user-attachments/assets/a3986940-6f6e-4f00-9a0c-8e669f0620fb)

https://github.com/wingyplus/zed-powershell/blob/1975ad28706cdf2d40d8a789fa9e35c49296c9e9/extension.toml#L7

**Comment by wingyplus** [comment]
Thank you for reporting!

This is fixed on [main](https://github.com/wingyplus/zed-powershell/blob/main/extension.toml#L7). Please wait on 0.2.0 that will release in 1-2 days.
